#Configuration file for GUIShop Plugin
#Do not change this number!
#You may break this plugin!
version: 2

general:
  database:
    #MySQL, MariaDB, local
    type: local
    database: database
    username: username
    password: passoword
    prefix: gshop_

dynamic_economy:
  #enabling dynamic pricing
  enabled: true
  #Seconds to control price
  timer: 60
  #Precent to increase/decrease price for buy/sell items
  increase_buy: 3
  decrease_buy: 5
  increase_sell: 3
  decrease_sell: 4
  #Precent from number of items to increase price
  needs_percent: 50

language:
  lore:
    - "Hello"
    - "Yello"
    - "Pedoooo"