#Configuration file for GUIShop Plugin
#Do not change this number!
#You may break this plugin!
Config version: 1

general:
  database:
    #MySQL, MariaDB, local
    type: local
    database: database
    username: username
    password: passoword
    prefix: gshop_

language:
  lore:
    - "Hello"
    - "Yello"
    - "Pedoooo"